// <copyright file="AddGitRepository.cs" company="ITANEO">
// Copyright (c) ITANEO (https://www.itaneo.com). All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace Hexalith.GitStorage.Commands.GitRepository;

using System.Runtime.Serialization;

using Hexalith.GitStorage.Aggregates.Enums;
using Hexalith.PolymorphicSerializations;

/// <summary>
/// Command to add a new GitRepository.
/// Creates the repository both locally and on the remote Git Server.
/// </summary>
/// <param name="Id">The composite key (pre-generated by caller: {OrganizationId}-{RepositoryName}).</param>
/// <param name="Name">The repository name.</param>
/// <param name="Description">Optional description for the repository.</param>
/// <param name="OrganizationId">Reference to the parent GitOrganization entity.</param>
/// <param name="Visibility">The visibility level of the repository.</param>
/// <param name="DefaultBranch">The default branch name (defaults to "main" if not specified).</param>
[PolymorphicSerialization]
public partial record AddGitRepository(
    string Id,
    [property: DataMember(Order = 2)] string Name,
    [property: DataMember(Order = 3)] string? Description,
    [property: DataMember(Order = 4)] string OrganizationId,
    [property: DataMember(Order = 5)] GitRepositoryVisibility Visibility = GitRepositoryVisibility.Private,
    [property: DataMember(Order = 6)] string? DefaultBranch = "main")
    : GitRepositoryCommand(Id);
