# OpenAPI Contract: Git Storage Account API Credentials
# Feature: 003-git-api-credentials
# Date: 2025-12-07

openapi: 3.0.3
info:
  title: Git Storage Account API Credentials
  description: API endpoints for managing Git API credentials on storage accounts
  version: 1.0.0

paths:
  /api/gitstorageaccount/{id}/api-credentials:
    put:
      summary: Change API credentials for a Git storage account
      description: Updates the server URL, access token, and provider type for connecting to a Git server API
      operationId: changeGitStorageAccountApiCredentials
      tags:
        - GitStorageAccount
      parameters:
        - name: id
          in: path
          required: true
          description: The Git storage account identifier
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeGitStorageAccountApiCredentialsRequest'
      responses:
        '202':
          description: Command accepted
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - insufficient permissions
        '404':
          description: Git storage account not found

    delete:
      summary: Clear API credentials from a Git storage account
      description: Removes all API credentials (server URL, access token, provider type) from the account
      operationId: clearGitStorageAccountApiCredentials
      tags:
        - GitStorageAccount
      parameters:
        - name: id
          in: path
          required: true
          description: The Git storage account identifier
          schema:
            type: string
      responses:
        '202':
          description: Command accepted
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - insufficient permissions
        '404':
          description: Git storage account not found

  /api/gitstorageaccount:
    post:
      summary: Add a new Git storage account
      description: Creates a new Git storage account with optional API credentials
      operationId: addGitStorageAccount
      tags:
        - GitStorageAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddGitStorageAccountRequest'
      responses:
        '202':
          description: Command accepted
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - insufficient permissions
        '409':
          description: Git storage account already exists

  /api/gitstorageaccount/{id}:
    get:
      summary: Get Git storage account details
      description: Retrieves details of a Git storage account including masked API credentials
      operationId: getGitStorageAccountDetails
      tags:
        - GitStorageAccount
      parameters:
        - name: id
          in: path
          required: true
          description: The Git storage account identifier
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GitStorageAccountDetailsResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - insufficient permissions
        '404':
          description: Git storage account not found

components:
  schemas:
    GitServerProviderType:
      type: string
      enum:
        - GitHub
        - Forgejo
        - Gitea
        - Generic
      description: The type of Git server platform

    ChangeGitStorageAccountApiCredentialsRequest:
      type: object
      required:
        - serverUrl
        - accessToken
        - providerType
      properties:
        serverUrl:
          type: string
          format: uri
          description: The base URL of the Git server API (must be HTTPS)
          example: "https://api.github.com"
        accessToken:
          type: string
          description: The authentication token for the Git server API
          minLength: 1
        providerType:
          $ref: '#/components/schemas/GitServerProviderType'

    AddGitStorageAccountRequest:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: Unique identifier for the storage account
          minLength: 1
        name:
          type: string
          description: Display name for the storage account
          minLength: 1
        comments:
          type: string
          description: Optional description or notes
          nullable: true
          maxLength: 1000
        serverUrl:
          type: string
          format: uri
          description: Optional base URL of the Git server API (must be HTTPS if provided)
          nullable: true
          example: "https://api.github.com"
        accessToken:
          type: string
          description: Optional authentication token (required if serverUrl is provided)
          nullable: true
        providerType:
          $ref: '#/components/schemas/GitServerProviderType'
          nullable: true
          description: Optional provider type (defaults to GitHub if credentials provided)

    GitStorageAccountDetailsResponse:
      type: object
      required:
        - id
        - name
        - disabled
      properties:
        id:
          type: string
          description: Unique identifier
        name:
          type: string
          description: Display name
        comments:
          type: string
          nullable: true
          description: Optional description
        disabled:
          type: boolean
          description: Whether the account is disabled
        serverUrl:
          type: string
          nullable: true
          description: The configured Git server API URL
        maskedAccessToken:
          type: string
          nullable: true
          description: Partially masked access token showing last 4 characters
          example: "••••••••abc1"
        providerType:
          $ref: '#/components/schemas/GitServerProviderType'
          nullable: true
        hasApiCredentials:
          type: boolean
          description: Whether API credentials are configured

    ValidationProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

tags:
  - name: GitStorageAccount
    description: Operations for managing Git storage accounts and their API credentials
