//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hexalith.GitStorage.Localizations {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GitRepository {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GitRepository() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hexalith.GitStorage.Localizations.GitRepository", typeof(GitRepository).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add new repository.
        /// </summary>
        public static string AddTitle {
            get {
                return ResourceManager.GetString("AddTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default Branch.
        /// </summary>
        public static string DefaultBranch {
            get {
                return ResourceManager.GetString("DefaultBranch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default branch is required.
        /// </summary>
        public static string DefaultBranchRequired {
            get {
                return ResourceManager.GetString("DefaultBranchRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Identifier required.
        /// </summary>
        public static string IdRequired {
            get {
                return ResourceManager.GetString("IdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last Synced.
        /// </summary>
        public static string LastSynced {
            get {
                return ResourceManager.GetString("LastSynced", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string ListTitle {
            get {
                return ResourceManager.GetString("ListTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name must be 1-100 characters, alphanumeric/hyphens/underscores/periods only, cannot start with period or end with .git.
        /// </summary>
        public static string NameInvalidFormat {
            get {
                return ResourceManager.GetString("NameInvalidFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Organization ID required.
        /// </summary>
        public static string OrganizationIdRequired {
            get {
                return ResourceManager.GetString("OrganizationIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remote ID.
        /// </summary>
        public static string RemoteId {
            get {
                return ResourceManager.GetString("RemoteId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SyncStatus {
            get {
                return ResourceManager.GetString("SyncStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Git Repositories {0}.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URL must be a valid HTTPS URL.
        /// </summary>
        public static string UrlInvalidFormat {
            get {
                return ResourceManager.GetString("UrlInvalidFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid visibility value.
        /// </summary>
        public static string VisibilityInvalid {
            get {
                return ResourceManager.GetString("VisibilityInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string VisibilityInternal {
            get {
                return ResourceManager.GetString("VisibilityInternal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string VisibilityPrivate {
            get {
                return ResourceManager.GetString("VisibilityPrivate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string VisibilityPublic {
            get {
                return ResourceManager.GetString("VisibilityPublic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Visibility is required.
        /// </summary>
        public static string VisibilityRequired {
            get {
                return ResourceManager.GetString("VisibilityRequired", resourceCulture);
            }
        }
    }
}
