// <copyright file="AddGitOrganization.cs" company="ITANEO">
// Copyright (c) ITANEO (https://www.itaneo.com). All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace Hexalith.GitStorage.Commands.GitOrganization;

using System.Runtime.Serialization;

using Hexalith.GitStorage.Aggregates.Enums;
using Hexalith.PolymorphicSerializations;

/// <summary>
/// Command to add a new GitOrganization.
/// Creates the organization both locally and on the remote Git Server.
/// </summary>
/// <param name="Id">The composite key (pre-generated by caller: {GitStorageAccountId}-{OrganizationName}).</param>
/// <param name="Name">The organization name.</param>
/// <param name="Description">Optional description for the organization.</param>
/// <param name="GitStorageAccountId">Reference to the parent GitStorageAccount entity.</param>
/// <param name="Visibility">The visibility level of the organization.</param>
[PolymorphicSerialization]
public partial record AddGitOrganization(
    string Id,
    [property: DataMember(Order = 2)] string Name,
    [property: DataMember(Order = 3)] string? Description,
    [property: DataMember(Order = 4)] string GitStorageAccountId,
    [property: DataMember(Order = 5)] GitOrganizationVisibility Visibility = GitOrganizationVisibility.Public)
    : GitOrganizationCommand(Id);